name: build and deploy
permissions:
  contents: read

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # build frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: build frontend
        working-directory: ./frontend
        run: |
          ./frontend.sh
